### ISSUE TITLE
Sequence error catching

### ISSUE THREAD

**Issue by 8bitskull** [britzl/ludobits#11]
I've fallen in love with coroutines through use of Sequence.

I realised that errors in Sequence weren't thrown as normal - with some research I now understand why: [https://forum.defold.com/t/defold-doesnt-show-any-error-and-stop-execution-of-the-oroutine-if-you-wrongly-send-message-from-module-msg-post-solved/3441/10](https://forum.defold.com/t/defold-doesnt-show-any-error-and-stop-execution-of-the-oroutine-if-you-wrongly-send-message-from-module-msg-post-solved/3441/10) 

Would it be possible to make Sequence throw errors? Doesn't look like errors are being caught currently and I'm not sure what to do to change that.

**Comment by britzl** [comment]
Yeah, coroutines are great!

Error handling is tricky though as like you pointed out the code in the coroutine is running in protected mode which means that errors will go undetected unless you check the return value every time you call coroutine.resume(). The sequence module check the return value and prints any errors, but I think perhaps it would make more sense to have something like 

     sequence.on_error(fn)

The provided function would get called when an error is detected. Is that the kind of thing you are looking for?

**Comment by 8bitskull** [comment]
I think so, but let me quickly describe my workflow/use case just to be sure.

Normally, I spend a few minutes writing code to implement something new. Then I test the build to see if it works as intended. Of course, more often than not there's an error first time around. The description of the error and the line number being reported instantly sets me on the right path.

Before I understood that coroutines run in protected mode, I would get stumped because execution of the build would stop but there would not be an error. I would assume it was a fault in my logic rather than syntax (or whatever else directly related to code execution) causing the issue. Now, armed with more understanding, I usually correctly assume that there is a code error to deal with within the coroutine, but it's still hard work because I have to review the entirety of my changes rather than jump directly to the offending line.

I think the above is uncontroversial, but I just wanted to clarify to be absolutely clear.

The ideal solution for me would be that Sequence throws errors like any other script. As an alternative, I would also be happy with a function I could call when I know there is an error so that I could get information about it as normal. This solution might be preferrable if it's more performant.

**Comment by britzl** [comment]
> throws errors like any other script

By this you mean an actual error() which you can catch using pcall() or through sys.set_error_handler()?

When an error occurs inside a sequence you should at least see the file and line number where it happens:

      DEBUG:SCRIPT: /examples/sequence/sequence.script:15: attempt to perform arithmetic on a nil value

**Comment by 8bitskull** [comment]
Um, you're right. I don't know what I experienced then. Unfortunately it was over a week ago so I can't remember exactly what happened / how to reproduce it. I would suggest we put a pin in this for now until I can provide an actual example. Can we close and then re-open issues? If so that would probably be best.

**Comment by britzl** [comment]
Yes, sure, let's close it for now. And re-open it if you find a repro case.

**Comment by britzl** [comment]
I did notice that wait_until_true() and wait_until_false() doesn't actual print an error. Are you using those functions?

**Comment by 8bitskull** [comment]
Yes, I am using both of those! I tried creating an error (e.g. performing arithmetic on a nil value) within wait_until_false() and it did print an error, however, so I remain confused.

**Comment by britzl** [comment]
Strange indeed. Well, lett's close the issue for now.
