### ISSUE TITLE
Increasing time gap in flow module

### ISSUE THREAD

**Issue by MinchukSergei** [britzl/ludobits#12]
In flow module while creating new instance of timer you use 0.016 delay.

After a little test:

init function:
```
timer.delay(0.016, true, function(self, handler, dt)
  timer_time = timer_time + dt
  print('timer: ' .. timer_time)
end)
```

update function:
```
update_time = update_time + dt
print('update: ' .. update_time)
```
The difference between timer_time and update_time keeps growing:
![image](https://user-images.githubusercontent.com/10199214/99182542-8fe0cb00-2746-11eb-86d3-c1be853059f3.png)

In other modules you using timer.delay(0... and in this case the gap is gone:
![image](https://user-images.githubusercontent.com/10199214/99182573-b999f200-2746-11eb-97e8-58aa5ae35652.png)

**Comment by britzl** [comment]
Thanks for pointing this out!
