### ISSUE TITLE
Savetable creates unreadable content

### ISSUE THREAD

**Issue by LachisSpaces** [britzl/ludobits#13]
The function savetable.save() creates unreadable files on my Windows 10 computer, see attached image.
I have also attached the file.

This problem does not happen in the older version 6.7.1

[savetable.zip](https://github.com/britzl/ludobits/files/5624518/savetable.zip)
![image](https://user-images.githubusercontent.com/31180883/100778858-d6514d80-3407-11eb-949b-ce87e75c0c23.png)

**Comment by britzl** [comment]
The default behaviour in newer versions is to save the table using sys.save(). This creates a binary file representing your table. You can also save the table using the io.* functions in which case the table will be encoded to JSON and stored as a string.

```
savetable.save(data, filename, savetable.FORMAT_IO)
savetable.save(data, filename, savetable.FORMAT_SYS)
```
