### ISSUE TITLE
flow gui_animate in defold 151

### ISSUE THREAD

**Issue by Insality** [britzl/ludobits#4]
After update, flow.gui_animate was broken
`You can only access gui.* functions and values from a gui script instance (.gui_script file)`
Is it issue from __instance__ remove from 151 update?

**Comment by britzl** [comment]
Hmm, are you creating the flow from a .script file but use gui.* functions?

Can you create a minimal repro case?

**Comment by Insality** [comment]
Nope, I am clone node and try animate it in single lua file, called from gui_script
I can create repro case, but later today

For now I am using you sequence module from ludobits for simple animations (instead flow)

**Comment by Insality** [comment]
Sorry, still no example now
But seems, problem is what I have global *flow.update()* in other collection
And *flow.start()* in another collection
So there is context mismatch

**Comment by britzl** [comment]
flow.update() is no longer needed and flagged as deprecated. It's an empty function. Please try to create an minimal repro case.

**Comment by britzl** [comment]
Old issue. Closing.
