### ISSUE TITLE
Can flow receive messages without waiting for new frame?

### ISSUE THREAD

**Issue by notbadgun** [britzl/ludobits#7]
I have two scripts that post messages each other. Scripts' `on_message` functions look ugly and unreadable so I decided to rework them using `flow`.

My old code usually posts and receives a few dozens messages in a *single frame*.

I found that `flow.until_message` waits for next frame after receiving the message. Therefore my new code requires a *few dozens frames* to complete --- this is too long for my game.

Is it a flaw by design? Can it be fixed? `flow` makes code look so much readable...

**Comment by britzl** [comment]
Good point. Fixed in https://github.com/britzl/ludobits/releases/tag/6.8.0
