### ISSUE TITLE
Mistake in logger usage description

### ISSUE THREAD

**Issue by jalhund** [britzl/ludobits#9]
In example written:
`log1.level(logger.WARN)`
But must be 
``logger.level(logger.WARN)``
Because created log instance have no level function. This function is only available in the entire module.
Links: 
[logger.lua](https://github.com/britzl/ludobits/blob/master/ludobits/m/logger.lua)
[logger.md](https://github.com/britzl/ludobits/blob/master/ludobits/m/logger.md) - mistake is here

**Comment by britzl** [comment]
Good point! Thanks. I've updated the readme
